version: "3.7"

services:

  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PORT=${DEVPORT}
    ports:
      - 4444:4444